### ISSUE TITLE
No chat box 50% of the time.  Messages don't get sent most of the time either.

### ISSUE THREAD

**Issue by djbielejeski** [angular-resource-sails/bunker#30]
When I load bunker, 50% of the time I do not get a chat box.  When I do get a chat box, I can type into it but nothing gets sent about 75% of the time. Seems to get fixed by refreshing a bunch and switching rooms.  Bunker is basically unusable for me in its current state. 

Browser: Chrome
Machines Tested: 3 (Home desktop, work laptop, personal laptop)

Screenshot
![bunker bug - ss 1](https://cloud.githubusercontent.com/assets/2463282/6484106/64222842-c23e-11e4-8c6e-a8aecc98cea7.png)

**Comment by JasonMore** [comment]
fixed now, Jason did something dumb
